IBM/container-registry-node-sdk

.secrets.baseline
.travis.yml

Uncomment the semver part of travis yaml.
Should also cause the package to be published.

fix(Project): Enable sem-ver step in Travis

---

.travis.yml

fix(Project): Use correct branch name for semver

---

.releaserc

SemVer internal config had `master` hardcoded as the branch name

fix(Project): Allow semver to run against main branch

---

.releaserc

Cribbed the new config from another team

fix(Project): semver config requires branches rather than branch

---

README.md

Mostly about beautifying the readme with badges
**Fixes:**

fix(Docs): Uncomment and fix the Readme links

---

README.md
container-registry/v1.ts
package-lock.json
test/integration/container-registry.v1.test.js

Regenerated from latest apidoc
**Fixes:** https://github.com/IBM/container-registry-node-sdk/issues/7
The apidoc updated resulted in a minor change to this SDK. The examples and integration tests for this route continued to work unchanged.

fix(Registry): Update getImageManifest definition

---

.travis.yml
README.md
package-lock.json
package.json

Removing unwanted step from CI

fix(project): Remove codecov steps

---

package-lock.json
package.json

Updates dependencies to resolve vulnerabilities
**Fixes:** N/A

fix(project): Update dependencies

---

.eslintrc.js
.travis.yml
package-lock.json
package.json

Updates all dependencies to latest, to remediate potential vulnerabilities
**Fixes:**  https://github.com/IBM/container-registry-node-sdk/issues/11

fix(project): update all dependencies

---

package-lock.json

Remediate issue identified by dependabot alert, by updating dependencies
**Fixes:**

fix(project): Updated dependencies to remediate vulns

---

package-lock.json

Dependency update to resolve an `npm audit` finding in minimist
**Fixes:**

fix(project): Update minimist dependency for vulnerability

---

.secrets.baseline
package-lock.json
package.json

Signed-off-by: James Hart <JHART@UK.ibm.com>
Updates dependencies to resolve potential vulnerabilities found by dependabot

fix(project): Update dependencies to resolve dependabot findings

---

package-lock.json

http-cache-semantics was found to be vulnerable

fix(project): upgrade vulnerable dependency

---

.pre-commit-config.yaml
container-registry/v1.ts
package-lock.json
package.json
test/unit/container-registry.v1.test.js

The eu-fr2 endpoint is now available.

Add eu-fr2 endpoint

---

package-lock.json

Fix vulnerability in follow-redirects by upgrading axios

fix(project): Remediate vulnerabilities

---

package-lock.json

Update packages using:
```
npm audit fix
```
**Fixes:** Vulnerability, specifically in `follow-redirects 1.15.4`
Dependencies are vulnerable
Dependencies are not vulnerable

build(deps): currency update

---

.travis.yml
container-registry/v1.ts
package-lock.json
package.json
test/unit/container-registry.v1.test.js
test/unit/vulnerability-advisor.v4.test.js
vulnerability-advisor/v4.ts

Bump sdk-core and axios for CVE-2024-39338
This also adds @ibm-cloud/sdk-test-utilities as a dev dependency per the sdk-core release notes for v5: https://github.com/IBM/node-sdk-core/releases/tag/v5.0.0
**Fixes:** N/A
Vulnerable dependency version
Patched dependency consumed

fix(project): Bump sdk-core and axios for CVE-2024-39338

---

package-lock.json
package.json

Bump cross-spawn to fix https://nvd.nist.gov/vuln/detail/CVE-2024-21538
Fixes: n/a

fix(project): bump cross-spawn for CVE-2024-21538

---

.secrets.baseline
package-lock.json
package.json

Updates axios and ibm-cloud-sdk-core
**Fixes:**
- CVE-2025-27152

fix(project): upgrades axios and ibm-cloud-sdk-core

---

package-lock.json
package.json

fix(project): upgrade ibm-cloud-sdk-core
